SolidariData/SolidariData/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('sdata.urls')),
    path('admin/', admin.site.urls),
]

SolidariData/sdata/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('sdata', views.home, name='home'),
    # Families paths:
    path('sdata/family', views.family_list, name='family_list'),  # List all families
    path('sdata/family/<int:pk>/', views.family_detail, name='family_detail'),  # View details of a specific family
    path('sdata/family/create/', views.family_create, name='family_create'),  # Create a new family
    path('sdata/family/<int:pk>/update/', views.family_update, name='family_update'),  # Update a specific family
    path('sdata/family/<int:pk>/delete/', views.family_delete, name='family_delete'),  # Delete a specific family
    #
    # Event URLs
    path('sdata/events/', views.event_list, name='event_list'),
    path('sdata/events/<int:pk>/', views.event_detail, name='event_detail'),
    path('sdata/events/create/', views.event_create, name='event_create'),
    path('sdata/events/<int:pk>/update/', views.event_update, name='event_update'),
    path('sdata/events/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('sdata/events/<int:event_pk>/toggle-institution/<int:institution_pk>/', views.toggle_institution_signup, name='toggle_institution_signup'),
    path('sdata/events/<int:event_pk>/families/', views.event_family_list, name='event_family_list'),
    path('sdata/events/<int:event_pk>/manage-families/', views.manage_event_families, name='manage_event_families'),
    path('sdata/events/<int:event_pk>/toggle-family-served/<int:family_pk>/', views.toggle_family_served, name='toggle_family_served'),
    path('sdata/events/<int:event_pk>/manage-served-status/', views.manage_served_status, name='manage_served_status'),
    path('sdata/events/<int:event_pk>/manage-family-institution/', views.manage_family_institution, name='manage_family_institution'),

    # Institution URLs
    path('sdata/institutions/', views.institution_list, name='institution_list'),
    path('sdata/institutions/<int:pk>/', views.institution_detail, name='institution_detail'),
    path('sdata/institutions/create/', views.institution_create, name='institution_create'),
    path('sdata/institutions/<int:pk>/update/', views.institution_update, name='institution_update'),
    path('sdata/institutions/<int:pk>/delete/', views.institution_delete, name='institution_delete'),

    # Institution Representative URLs
    path('sdata/institutions/<int:institution_pk>/representatives/', views.institution_representative_list, name='institution_representative_list'),
    path('sdata/institutions/<int:institution_pk>/representatives/create/', views.institution_representative_create, name='institution_representative_create'),
    path('sdata/institutions/<int:institution_pk>/representatives/<int:pk>/update/', views.institution_representative_update, name='institution_representative_update'),
    path('sdata/institutions/<int:institution_pk>/representatives/<int:pk>/delete/', views.institution_representative_delete, name='institution_representative_delete'),

    # InstitutionEvent URLs
    path('sdata/institution-events/', views.institution_event_list, name='institution_event_list'),
    path('sdata/institution-events/create/', views.institution_event_create, name='institution_event_create'),
    path('sdata/institution-events/<int:pk>/delete/', views.institution_event_delete, name='institution_event_delete'),

    # FamilyEvent URLs
    path('sdata/family-events/', views.family_event_list, name='family_event_list'),
    path('sdata/family-events/create/', views.family_event_create, name='family_event_create'),
    path('sdata/family-events/<int:pk>/delete/', views.family_event_delete, name='family_event_delete'),

    # FamilyEventInstitution URLs
    path('sdata/family-event-institutions/', views.family_event_institution_list, name='family_event_institution_list'),
    path('sdata/family-event-institutions/create/', views.family_event_institution_create, name='family_event_institution_create'),
    path('sdata/family-event-institutions/<int:pk>/delete/', views.family_event_institution_delete, name='family_event_institution_delete'),
]

SolidariData/sdata/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Family(models.Model):
    BRAZILIAN_STATES = [('AC', 'Acre'),('AL', 'Alagoas'),('AP', 'Amapá'),('AM', 'Amazonas'),('BA', 'Bahia'),('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),('ES', 'Espírito Santo'),('GO', 'Goiás'),('MA', 'Maranhão'),('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),('MG', 'Minas Gerais'),('PA', 'Pará'),('PB', 'Paraíba'),('PR', 'Paraná'),('PE', 'Pernambuco'),
        ('PI', 'Piauí'),('RJ', 'Rio de Janeiro'),('RN', 'Rio Grande do Norte'),('RS', 'Rio Grande do Sul'),('RO', 'Rondônia'),
        ('RR', 'Roraima'),('SC', 'Santa Catarina'),('SP', 'São Paulo'),('SE', 'Sergipe'),('TO', 'Tocantins'),
    ]
    family_id = models.AutoField(primary_key=True)
    family_representative_name = models.CharField(max_length=100, db_index=True)
    family_representative_gender = models.CharField(max_length=10, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], blank=True)
    family_representative_birthdate = models.DateField(null=True, blank=True)
    family_representative_id = models.CharField(max_length=14, unique=True)
    family_address_street = models.CharField(max_length=65)
    family_address_number = models.CharField(max_length=10)
    family_address_neighborhood = models.CharField(max_length=65)
    family_address_city = models.CharField(max_length=65)
    family_address_state = models.CharField(max_length=2, choices=BRAZILIAN_STATES, blank=True, default='SP')
    family_address_zipcode = models.CharField(max_length=10, blank=True)
    family_address_complement = models.CharField(max_length=255, blank=True)
    family_phone = models.CharField(max_length=15, blank=True)
    family_note = models.TextField(blank=True)
    family_created = models.DateTimeField(auto_now_add=True)
    family_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.family_representative_name


class Relative(models.Model):
    GRAU_DE_PARENTESCO = [
        ('pai', 'Pai'),
        ('mae', 'Mãe'),
        ('irmao/irmã', 'Irmão/Irmã'),
        ('filho/filha', 'Filho/Filha'),
        ('cônjuge', 'Cônjuge'),
        ('avô/avó', 'Avô/Avó'),
        ('neto/neta', 'Neto/Neta'),
        ('outro', 'Outro')
    ]
    relative_id = models.AutoField(primary_key=True, editable=False)
    relative_name = models.CharField(max_length=100, db_index=True)
    relative_gender = models.CharField(max_length=10, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], blank=True)
    relative_birthdate = models.DateField(null=True, blank=True)
    relative_relationship = models.CharField(max_length=50, blank=True, choices=GRAU_DE_PARENTESCO)
    relative_family = models.ForeignKey(Family, on_delete=models.CASCADE, related_name="relatives")
    relative_phone = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.relative_name


class Institution(models.Model):
    institution_id = models.AutoField(primary_key=True)
    institution_name = models.CharField(max_length=100, db_index=True)
    institution_type = models.CharField(max_length=11, choices=[('comunitária', 'Comunitária'), ('privada', 'Privada'), ('pública', 'Pública'), ('religiosa', 'Religiosa'), ('outra', 'Outra')], blank=True)
    institution_cnpj = models.CharField(max_length=18, unique=True, blank=True)
    institution_address_street = models.CharField(max_length=65)
    institution_address_number = models.CharField(max_length=10)
    institution_address_neighborhood = models.CharField(max_length=65)
    institution_address_city = models.CharField(max_length=65)
    institution_address_state = models.CharField(max_length=2, choices=Family.BRAZILIAN_STATES, blank=True, default='SP')
    institution_address_zipcode = models.CharField(max_length=10, blank=True)
    institution_address_complement = models.CharField(max_length=255, blank=True)
    institution_phone = models.CharField(max_length=15, blank=True)
    institution_email = models.EmailField(blank=True)
    institution_website = models.URLField(blank=True)
    institution_social_media = models.CharField(max_length=255, blank=True)
    institution_description = models.TextField(blank=True)
    institution_note = models.TextField(blank=True)
    institution_created = models.DateTimeField(auto_now_add=True)
    institution_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.institution_name

class InstitutionRepresentative(models.Model):
    institution_representative_id = models.AutoField(primary_key=True)
    institution_representative_name = models.CharField(max_length=100, db_index=True)
    institution_representative_gender = models.CharField(max_length=10, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], blank=True)
    institution_representative_birthdate = models.DateField(null=True, blank=True)
    institution_representative_id_number = models.CharField(max_length=14, unique=True)
    institution_representative_address_street = models.CharField(max_length=65)
    institution_representative_address_number = models.CharField(max_length=10)
    institution_representative_address_neighborhood = models.CharField(max_length=65)
    institution_representative_address_city = models.CharField(max_length=65)
    institution_representative_address_state = models.CharField(max_length=2, choices=Family.BRAZILIAN_STATES, blank=True, default='SP')
    institution_representative_address_zipcode = models.CharField(max_length=10, blank=True)
    institution_representative_address_complement = models.CharField(max_length=255, blank=True)
    institution_representative_phone = models.CharField(max_length=15, blank=True)
    institution_representative_email = models.EmailField(blank=True)
    institution_representative_note = models.TextField(blank=True)
    institution_representative_institution = models.ForeignKey(Institution, on_delete=models.CASCADE, related_name="representatives")
    institution_representative_created = models.DateTimeField(auto_now_add=True)
    institution_representative_updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.institution_representative_name


class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    event_name = models.CharField(max_length=100, db_index=True)
    event_date = models.DateField()
    event_location_street = models.CharField(max_length=65)
    event_location_number = models.CharField(max_length=10)
    event_location_neighborhood = models.CharField(max_length=65)
    event_location_city = models.CharField(max_length=65)
    event_location_state = models.CharField(max_length=2, choices=Family.BRAZILIAN_STATES, blank=True, default='SP')
    event_location_zipcode = models.CharField(max_length=10, blank=True)
    event_location_complement = models.CharField(max_length=255, blank=True)
    event_institution = models.ForeignKey(
        Institution, 
        on_delete=models.SET_NULL,  # Use SET_NULL to allow the field to be null if the institution is deleted
        blank=True, 
        null=True,  # Add null=True to allow null values
        related_name="events"
    )
    event_website = models.URLField(blank=True)
    event_social_media = models.CharField(max_length=255, blank=True)
    event_contact_person = models.CharField(max_length=100, blank=True)
    event_contact_phone = models.CharField(max_length=15, blank=True)
    event_contact_email = models.EmailField(blank=True)
    event_description = models.TextField(blank=True)
    event_note = models.TextField(blank=True)
    event_created = models.DateTimeField(auto_now_add=True)
    event_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.event_name

class InstitutionEvent(models.Model):
    institution_event_id = models.AutoField(primary_key=True)
    institution_event_institution = models.ForeignKey(Institution, on_delete=models.CASCADE, related_name="institution_events", db_index=True)
    institution_event_event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="institution_events", db_index=True)
    institution_event_registration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.institution_event_institution} - {self.institution_event_event}"

class FamilyEvent(models.Model):
    family_event_id = models.AutoField(primary_key=True)
    family_event_family = models.ForeignKey(Family, on_delete=models.CASCADE, related_name="family_events", db_index=True)
    family_event_event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="family_events", db_index=True)
    family_event_registration_date = models.DateTimeField(auto_now_add=True)
    served = models.BooleanField(default=False)  # Field to track if the family was served

    def __str__(self):
        return f"{self.family_event_family} - {self.family_event_event}"

class FamilyEventInstitution(models.Model):
    family_event = models.OneToOneField(FamilyEvent, on_delete=models.CASCADE, related_name="institution_assignment", db_index=True)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE, related_name="assigned_family_events", db_index=True)
    assigned_date = models.DateTimeField(auto_now_add=True)
    served = models.BooleanField(default=False) 


    def clean(self):
        if not self.family_event:
            raise ValidationError("A FamilyEvent must be associated with this assignment.")
        if not self.institution:
            raise ValidationError("An Institution must be assigned to this FamilyEvent.")

    def __str__(self):
        return f"{self.family_event} - {self.institution}"

SolidariData/sdata/templates/sdata/event_confirm_delete.html
{% extends "sdata/base.html" %}
{% block content %}

<h1>Remover Evento</h1>
<p>Você tem certeza de que deseja remover o evento "{{ event.event_name }}"?</p>

<form method="post">
    {% csrf_token %}
    <button type="button" class="btn-secondary" onclick="window.location.href='{% url 'event_list' %}'">
        Cancelar
    </button>
    <button class="btn-danger" type="submit">Sim, remover</button>
</form>

{% endblock %}

SolidariData/sdata/templates/sdata/event_detail.html
{% extends "sdata/base.html" %}
{% block content %}

<h1>Detalhes do Evento</h1>

<!-- Event Details -->
<fieldset>
    <legend>Informações do Evento</legend>
    <div class="form-row">
        <div class="form-group">
            <label for="event_name">Nome:</label>
            <input type="text" id="event_name" name="event_name" 
                   value="{{ event.event_name }}" readonly class="form-control">
        </div>
        <div class="form-group-1">
            <label for="event_date">Data:</label>
            <input type="text" id="event_date" name="event_date" 
                   value="{{ event.event_date }}" readonly class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label for="event_institution">Instituição:</label>
            <input type="text" id="event_institution" name="event_institution" 
                   value="{{ event.event_institution|default_if_none:'Nenhuma' }}" readonly class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label for="event_location_street">Rua:</label>
            <input type="text" id="event_location_street" name="event_location_street" 
                   value="{{ event.event_location_street }}" readonly class="form-control">
        </div>
        <div class="form-group-1">
            <label for="event_location_number">Número:</label>
            <input type="text" id="event_location_number" name="event_location_number" 
                   value="{{ event.event_location_number }}" readonly class="form-control">
        </div>
        <div class="form-group">
            <label for="event_location_neighborhood">Bairro:</label>
            <input type="text" id="event_location_neighborhood" name="event_location_neighborhood" 
                   value="{{ event.event_location_neighborhood }}" readonly class="form-control">
        </div>
        <div class="form-group">
            <label for="event_location_city">Cidade:</label>
            <input type="text" id="event_location_city" name="event_location_city" 
                   value="{{ event.event_location_city }}" readonly class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group-1">
            <label for="event_location_state">Estado:</label>
            <input type="text" id="event_location_state" name="event_location_state" 
                   value="{{ event.get_event_location_state_display }}" readonly class="form-control">
        </div>
        <div class="form-group-1">
            <label for="event_location_zipcode">CEP:</label>
            <input type="text" id="event_location_zipcode" name="event_location_zipcode" 
                   value="{{ event.event_location_zipcode }}" readonly class="form-control">
        </div>
        <div class="form-group">
            <label for="event_location_complement">Complemento:</label>
            <input type="text" id="event_location_complement" name="event_location_complement" 
                   value="{{ event.event_location_complement }}" readonly class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group">
            <label for="event_contact_person">Pessoa de Contato:</label>
            <input type="text" id="event_contact_person" name="event_contact_person" 
                   value="{{ event.event_contact_person }}" readonly class="form-control">
        </div>
        <div class="form-group">
            <label for="event_contact_phone">Telefone de Contato:</label>
            <input type="text" id="event_contact_phone" name="event_contact_phone" 
                   value="{{ event.event_contact_phone }}" readonly class="form-control">
        </div>
        <div class="form-group">
            <label for="event_contact_email">Email de Contato:</label>
            <input type="text" id="event_contact_email" name="event_contact_email" 
                   value="{{ event.event_contact_email }}" readonly class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label for="event_description">Descrição:</label>
        <textarea id="event_description" name="event_description" readonly class="form-control">{{ event.event_description }}</textarea>
    </div>
    <div class="form-group">
        <label for="event_note">Notas:</label>
        <textarea id="event_note" name="event_note" readonly class="form-control">{{ event.event_note }}</textarea>
    </div>
</fieldset>

<!-- Signed-Up Institutions -->
<fieldset>
    <legend>Instituições Inscritas</legend>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Tipo</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            {% for institution in signed_up_institutions %}
            <tr>
                <td style="width: 20px">{{ institution.institution_id }}</td>
                <td style="width: 20%">{{ institution.institution_name }}</td>
                <td style="width: 10%">{{ institution.get_institution_type_display }}</td>
                <td>{{ institution.institution_description|default_if_none:"Sem descrição" }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4" style="text-align: center;">Nenhuma instituição inscrita.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</fieldset>

<!-- Form actions -->
<div class="form-actions">
    <div class="button">
        <button type="button" class="btn-secondary" onclick="window.location.href='{% url 'event_family_list' event.pk %}'">
            Ver Famílias no Evento
        </button>
        <button type="button" class="btn-secondary" onclick="window.location.href='{% url 'event_list' %}'">
            Voltar
        </button>
        <button type="button" class="btn-primary" onclick="window.location.href='{% url 'event_update' event.pk %}'">
            Editar
        </button>
        <button type="button" class="btn-danger" onclick="window.location.href='{% url 'event_delete' event.pk %}'">
            Excluir
        </button>
    </div>
</div>



{% endblock %}

SolidariData/sdata/templates/sdata/event_family_list.html
{% extends "sdata/base.html" %}
{% block content %}

<h1>Famílias no Evento: {{ event.event_name }}</h1>

<!-- Table of families in the event -->
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Endereço</th>
            <th>Atendido</th>
        </tr>
    </thead>
    <tbody>
        {% for family_event in families_in_event %}
        <tr>
            <td>{{ family_event.family_event_family.family_id }}</td>
            <td>{{ family_event.family_event_family.family_representative_name }}</td>
            <td>{{ family_event.family_event_family.family_phone }}</td>
            <td>{{ family_event.family_event_family.family_address_street }}, {{ family_event.family_event_family.family_address_number }} - {{ family_event.family_event_family.family_address_city }}</td>
            <td>
                {% if family_event.served %}
                    Sim
                {% else %}
                    Não
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5" style="text-align: center;">Nenhuma família associada a este evento.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Buttons to manage families, served status, and institution assignments -->
<div class="form-actions">
    <button type="button" class="btn-secondary" onclick="window.location.href='{% url 'event_detail' event.pk %}'">
        Detalhes do Evento
    </button>
    <button type="button" class="btn-primary" onclick="window.location.href='{% url 'manage_event_families' event.pk %}'">
        Gerenciar Famílias no Evento
    </button>
    <button type="button" class="btn-primary" onclick="window.location.href='{% url 'manage_served_status' event.pk %}'">
        Gerenciar Status de Atendimento
    </button>
    <button type="button" class="btn-primary" onclick="window.location.href='{% url 'manage_family_institution' event.pk %}'">
        Gerenciar Famílias por Instituição
    </button>
</div>

{% endblock %}

SolidariData/sdata/templates/sdata/event_form.html
{% extends "sdata/base.html" %}
{% block content %}

<h1>{{ form.instance.pk|default:"Cadastro de evento" }}</h1>
<form method="post" class="form-container">
    {% csrf_token %}
    
    <!-- Event Form -->
    <fieldset>
        <legend>Informações do Evento</legend>
        <div class="form-row">
            <div class="form-group">
                <label for="event_name">Nome do Evento:</label>
                {{ form.event_name }}
                {% for error in form.event_name.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group-1">
                <label for="event_date">Data do Evento:</label>
                {{ form.event_date }}
                {% for error in form.event_date.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group-2">
                <label for="event_location_street">Rua:</label>
                {{ form.event_location_street }}
                {% for error in form.event_location_street.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group-1">
                <label for="event_location_number">Número:</label>
                {{ form.event_location_number }}
                {% for error in form.event_location_number.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="event_location_neighborhood">Bairro:</label>
                {{ form.event_location_neighborhood }}
                {% for error in form.event_location_neighborhood.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="event_location_city">Cidade:</label>
                {{ form.event_location_city }}
                {% for error in form.event_location_city.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group-1">
                <label for="event_location_state">Estado:</label>
                {{ form.event_location_state }}
                {% for error in form.event_location_state.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group-1">
                <label for="event_location_zipcode">CEP:</label>
                {{ form.event_location_zipcode }}
                {% for error in form.event_location_zipcode.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="event_location_complement">Complemento:</label>
                {{ form.event_location_complement }}
                {% for error in form.event_location_complement.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                <label for="event_institution">Instituição Responsável pelo Evento:</label>
                {{ form.event_institution }}
                {% for error in form.event_institution.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                <label for="event_contact_person">Pessoa de Contato:</label>
                {{ form.event_contact_person }}
                {% for error in form.event_contact_person.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="event_contact_phone">Telefone de Contato:</label>
                {{ form.event_contact_phone }}
                {% for error in form.event_contact_phone.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="event_contact_email">Email de Contato:</label>
                {{ form.event_contact_email }}
                {% for error in form.event_contact_email.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                <label for="event_description">Descrição:</label>
                {{ form.event_description }}
                {% for error in form.event_description.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="event_note">Notas:</label>
                {{ form.event_note }}
                {% for error in form.event_note.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
    </fieldset>

    <!-- Institution Signup Section -->
    <fieldset>
        <legend>Inscrever Instituições</legend>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Tipo</th>
                    <th>Descrição</th>
                    <th>Inscrição</th>
                </tr>
            </thead>
            <tbody>
                {% for institution in institutions %}
                <tr>
                    <td>{{ institution.institution_id }}</td>
                    <td>{{ institution.institution_name }}</td>
                    <td>{{ institution.get_institution_type_display }}</td>
                    <td>{{ institution.institution_description|default_if_none:"Sem descrição" }}</td>
                    <td>
                        <label class="switch">
                            <input type="checkbox" name="signed_up_institutions" value="{{ institution.pk }}" 
                                   {% if institution.pk in signed_up_institutions %}checked{% endif %}>
                            <span class="slider round"></span>
                        </label>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5" style="text-align: center;">Nenhuma instituição disponível.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </fieldset>

    <!-- Buttons -->
    <div class="form-actions">
        <div class="button">
            <button type="button" class="btn-secondary" onclick="window.location.href='{% url 'event_list' %}'">Voltar</button>
            <button type="submit" class="btn-primary">Gravar alterações</button>
        </div>
    </div>
</form>

<script>
    document.querySelectorAll('.switch input[type="checkbox"]').forEach(function(toggle) {
        toggle.addEventListener('change', function() {
            const eventId = this.dataset.eventId;
            const institutionId = this.dataset.institutionId;
            const url = `/sdata/events/${eventId}/toggle-institution/${institutionId}/`;

            fetch(url, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
            .then(response => response.json())
            .catch(error => console.error('Erro:', error));
        });
    });
</script>

{% endblock %}

SolidariData/sdata/templates/sdata/family_confirm_delete.html
{% extends "sdata/base.html" %}
{% block content %}

<h1>Remover Família</h1>
<p>Você tem certeza de que deseja remover a família representada por "{{ family.family_representative_name }}"?</p>

<form method="post">
    {% csrf_token %}
    <button type="button" class="btn-secondary" onclick="window.location.href='{% url 'family_list' %}'">
        Cancelar
    </button>
    <button class="btn-danger type="submit">Sim, remover</button>
</form>

{% endblock %}

SolidariData/sdata/templates/sdata/home.html
{% extends "sdata/base.html" %}
{% block content %}
<p> Olá. Essa é a tela inicial.</p>


{% endblock %}